In [1]:
# Importing relevant libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
# Importing data from the dataset
Emp_Per=pd.read_excel('INX_Future_Inc_Employee_Performance_CDS_Project2_Data_V1.8.xls')
#Reading the first 3 rows
Emp_Per.head(3)

EmpNumber  Age Gender EducationBackground MaritalStatus EmpDepartment  \
0  E1001000   32   Male           Marketing        Single         Sales   
1  E1001006   47   Male           Marketing        Single         Sales   
2  E1001007   40   Male       Life Sciences       Married         Sales   

        EmpJobRole BusinessTravelFrequency  DistanceFromHome  \
0  Sales Executive           Travel_Rarely                10   
1  Sales Executive           Travel_Rarely                14   
2  Sales Executive       Travel_Frequently                 5   

   EmpEducationLevel        ...          EmpRelationshipSatisfaction  \
0                  3        ...                                    4   
1                  4        ...                                    4   
2                  4        ...                                    3   

   TotalWorkExperienceInYears  TrainingTimesLastYear  EmpWorkLifeBalance  \
0                          10                      2                   2   
1                          20                      2                   3   
2                          20                      2                   3   

   ExperienceYearsAtThisCompany  ExperienceYearsInCurrentRole  \
0                            10                             7   
1                             7                             7   
2                            18                            13   

  YearsSinceLastPromotion  YearsWithCurrManager  Attrition  PerformanceRating  
0                       0                     8         No                  3  
1                       1                     7         No                  3  
2                       1                    12         No                  4  

[3 rows x 28 columns]

In [2]:
# To convert all the features into INT with Label encoder
Emp_Per.Gender=le.fit_transform(Emp_Per.Gender)
Emp_Per.EducationBackground=le.fit_transform(Emp_Per.EducationBackground)
Emp_Per.MaritalStatus=le.fit_transform(Emp_Per.MaritalStatus)
Emp_Per.BusinessTravelFrequency=le.fit_transform(Emp_Per.BusinessTravelFrequency)
Emp_Per.OverTime=le.fit_transform(Emp_Per.OverTime)
Emp_Per.EmpJobRole=le.fit_transform(Emp_Per.EmpJobRole)
Emp_Per.EmpDepartment=le.fit_transform(Emp_Per.EmpDepartment)
Emp_Per.Attrition=le.fit_transform(Emp_Per.Attrition)

In [3]:
#Seting the target and predictor variables
X=Emp_Per.loc[:,'Age':'Attrition']
y=Emp_Per.loc[:,'PerformanceRating']

- We then split the dataset into two sets: training set and testing set. As the name implies, the training set will be used when training the model and the testing to test its predictive capability.

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=5)

In [5]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 900 entries, 811 to 867
Data columns (total 26 columns):
Age                             900 non-null int64
Gender                          900 non-null int64
EducationBackground             900 non-null int64
MaritalStatus                   900 non-null int64
EmpDepartment                   900 non-null int64
EmpJobRole                      900 non-null int64
BusinessTravelFrequency         900 non-null int64
DistanceFromHome                900 non-null int64
EmpEducationLevel               900 non-null int64
EmpEnvironmentSatisfaction      900 non-null int64
EmpHourlyRate                   900 non-null int64
EmpJobInvolvement               900 non-null int64
EmpJobLevel                     900 non-null int64
EmpJobSatisfaction              900 non-null int64
NumCompaniesWorked              900 non-null int64
OverTime                        900 non-null int64
EmpLastSalaryHikePercent        900 non-null int64
EmpRelationshipSatisfactio

- All the features in this dataset converted into INT datatype

In [18]:
# To check the Shape of X_train
X_train.shape

(840, 26)

In [19]:
# To check the Shape of X_test
X_test.shape

(360, 26)

In [20]:
# To check the Shape of y_train
y_train.shape

(840,)

In [21]:
# To check the Shape of y_test
y_test.shape

(360,)

 ### The Random Forest is chosen over other algorithms because it uses the entire dataset optimally which reduces bias error. The algorithm is also famous for providing maximum reduction in variance as it gives the average output from an ensemble of several decision trees,hence the name ‘Random Forest’.

- We then train the Random Forest Classifier model:

In [6]:
# Train the Random forest classifoer
from sklearn.ensemble import RandomForestClassifier
RFC= RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=500)
RFC.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=2,
            oob_score=True, random_state=None, verbose=0, warm_start=False)

# Predicting Model 

In [7]:
#Applying Calssifier to Test data
y_predict=RFC.predict(X_test)
y_predict

array([3, 2, 3, 3, 3, 3, 3, 3, 2, 4, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 2, 3,
       3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 3, 2, 3, 3,
       3, 3, 2, 2, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 2, 3, 3, 3, 3,
       3, 3, 2, 3, 3, 3, 3, 3, 4, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3,
       3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 4, 3, 2, 3, 3, 3,
       3, 4, 3, 3, 2, 4, 3, 3, 2, 2, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 3, 3, 4, 3, 4,
       3, 4, 3, 4, 2, 3, 3, 3, 3, 3, 4, 4, 3, 2, 3, 3, 3, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3,
       3, 3, 4, 2, 3, 4, 3, 3, 2, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       4, 3, 2, 3, 3, 2, 3, 3, 4, 3, 3, 4, 3, 2, 3, 3, 2, 3, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 2, 3, 4, 3, 3, 3, 2, 3, 2, 3, 2, 3, 3, 2, 4, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 2, 3, 3, 3], d

In [8]:
# Calculating Accuracy Score
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
acc=accuracy_score(y_test,y_predict)
acc

0.9333333333333333

- There are very few mis -classifications and the precision rates for all the values are very high as seen from the below output  and it implies that our model is highly accurate.

In [9]:
# Classification Report
cr=classification_report(y_test,y_predict)
print(cr)

             precision    recall  f1-score   support

          2       0.88      0.88      0.88        48
          3       0.95      0.97      0.96       224
          4       0.91      0.75      0.82        28

avg / total       0.93      0.93      0.93       300



In [10]:
cm=confusion_matrix(y_test,y_predict)
print(cm)

[[ 42   6   0]
 [  5 217   2]
 [  1   6  21]]


In [11]:
#Cross Validation

pd.crosstab(y_test,y_predict,rownames=['Actual'],colnames=['Prediction'],margins=True)

Prediction   2    3   4  All
Actual                      
2           42    6   0   48
3            5  217   2  224
4            1    6  21   28
All         48  229  23  300